### ISSUE TITLE
Plugin action not activated (grayed out)

### ISSUE THREAD

**Issue by gesmit74** [kcl-lang/intellij-kcl#32]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

open kcl file, right mouse click

### 2. What did you expect to see? (Required)
working action for kcl files

### 3. What did you see instead (Required)
Grayed out action for KCL files

### 4. What is your KCL components version? (Required)
0.1.18

Only syntax highlight seems to be working, no coding assistance, auto-complete
In my idea.log:

2024-07-08 11:43:38,339 [3351812] SEVERE - #io.kusionstack.kcl.action.FormatDirectoryAction - `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'io.kusionstack.kcl.action.FormatDirectoryAction' must override `getActionUpdateThread()` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: io.kusionstack.kcl]
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'io.kusionstack.kcl.action.FormatDirectoryAction' must override `getActionUpdateThread()` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: io.kusionstack.kcl]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:199)
2024-07-08 11:43:38,339 [3351812] SEVERE - #io.kusionstack.kcl.action.FormatSingleFileAction - `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'io.kusionstack.kcl.action.FormatSingleFileAction' must override `getActionUpdateThread()` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: io.kusionstack.kcl]
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'io.kusionstack.kcl.action.FormatSingleFileAction' must override `getActionUpdateThread()` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: io.kusionstack.kcl]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:199)
2024-07-08 11:43:38,385 [3351858] SEVERE - #io.kusionstack.kcl.action.FormatDirectoryAction - PhpStorm 2024.1.4  Build #PS-241.18034.69
2024-07-08 11:43:38,385 [3351858] SEVERE - #io.kusionstack.kcl.action.FormatSingleFileAction - PhpStorm 2024.1.4  Build #PS-241.18034.69
2024-07-08 11:43:38,385 [3351858] SEVERE - #io.kusionstack.kcl.action.FormatDirectoryAction - JDK: 17.0.11; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2024-07-08 11:43:38,385 [3351858] SEVERE - #io.kusionstack.kcl.action.FormatSingleFileAction - JDK: 17.0.11; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2024-07-08 11:43:38,386 [3351859] SEVERE - #io.kusionstack.kcl.action.FormatDirectoryAction - OS: Linux
2024-07-08 11:43:38,386 [3351859] SEVERE - #io.kusionstack.kcl.action.FormatSingleFileAction - OS: Linux
2024-07-08 11:43:38,386 [3351859] SEVERE - #io.kusionstack.kcl.action.FormatDirectoryAction - Plugin to blame: KCL version: 0.1.18
2024-07-08 11:43:38,386 [3351859] SEVERE - #io.kusionstack.kcl.action.FormatSingleFileAction - Plugin to blame: KCL version: 0.1.18
2024-07-08 11:43:38,387 [3351860] SEVERE - #io.kusionstack.kcl.action.FormatDirectoryAction - Last Action: Back
2024-07-08 11:43:38,387 [3351860] SEVERE - #io.kusionstack.kcl.action.FormatSingleFileAction - Last Action: Back
2024-07-08 11:43:38,556 [3352029]   INFO - #io.kusionstack.kcl.util.KCLBinaryUtil - KCL command kcl location: /usr/local/bin/kcl
2024-07-08 11:43:41,071 [3354544] SEVERE - #io.kusionstack.kcl.action.FormatSingleFileAction - `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'io.kusionstack.kcl.action.FormatSingleFileAction' must override `getActionUpdateThread()` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: io.kusionstack.kcl]
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'io.kusionstack.kcl.action.FormatSingleFileAction' must override `getActionUpdateThread()` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: io.kusionstack.kcl]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:199)
2024-07-08 11:43:41,072 [3354545] SEVERE - #io.kusionstack.kcl.action.FormatSingleFileAction - PhpStorm 2024.1.4  Build #PS-241.18034.69
2024-07-08 11:43:41,072 [3354545] SEVERE - #io.kusionstack.kcl.action.FormatSingleFileAction - JDK: 17.0.11; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2024-07-08 11:43:41,073 [3354546] SEVERE - #io.kusionstack.kcl.action.FormatSingleFileAction - OS: Linux
2024-07-08 11:43:41,073 [3354546] SEVERE - #io.kusionstack.kcl.action.FormatSingleFileAction - Plugin to blame: KCL version: 0.1.18
2024-07-08 11:43:41,073 [3354546] SEVERE - #io.kusionstack.kcl.action.FormatSingleFileAction - Last Action: Back

**Comment by He1pa** [comment]
Sorry, what is your Intellij version?

**Comment by He1pa** [comment]
I am trying to fix this problem. In addition, PhpStorm can try to use this https://github.com/kcl-lang/intellij-kcl-lsp, you can search KCL-LSP in the marketplace to get it

**Comment by gesmit74** [comment]
Thanks for the suggestion. Result is almost the same, no formatting ( also grayed out ) and some suggestions but mostly unusable. File and folder structure is not recognized / read, so almost everything is marked invalid

**Comment by He1pa** [comment]
hi, I have fixed this issue in #33 and uploaded a new version to the plugin market. But according to experience, it usually takes two working days for the review to be approved.
