### ISSUE TITLE
jetbarins家的IDE 插件很不稳定，没有vcscode版本的插件稳定， 我们研发用的IntelliJ 比较多，经常出现各种问题，稳定性不是很好，能不能给优化一版本。

### ISSUE THREAD

**Issue by cx2c** [kcl-lang/intellij-kcl#37]
以下是goland插件的报错。
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'io.kusionstack.kcl.action.FormatDirectoryAction' must override `getActionUpdateThread()` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: io.kusionstack.kcl]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:201)

**Comment by He1pa** [comment]
插件的版本是什么，之前在 https://github.com/kcl-lang/intellij-kcl/pull/33 修复过一次。
插件的问题近期在准备优化了，后续会重新实现基于 lsp 的插件，功能会有优化。 具体的计划: https://github.com/kcl-lang/intellij-kcl-lsp/issues/3

**Comment by cx2c** [comment]
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'io.kusionstack.kcl.action.FormatSingleFileAction' must override `getActionUpdateThread()` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: io.kusionstack.kcl-lsp]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:201)


tke.ops.dev ➜ ~ kcl-language-server version
Version: 0.10.0-beta.2-c020ab3eb4b9179219d6837a57f5d323
Platform: x86_64-apple-darwin
GitCommit: 42e1b672bc79b36fa03dad71b8fd235b8d3fdb5a

tke.ops.dev ➜ ~ kcl version
0.10.0-rc.1-darwin-amd64

![image](https://github.com/user-attachments/assets/adef7cb5-3558-4d31-a804-9e4f9443f85f)

**Comment by He1pa** [comment]
我们刚刚release了 0.3.0 版本，在这个插件中集成了 LSP，大部分常用功能与 VSCode 一致。目前插件市场正在审核中（通常需要2个工作日），审核完成后可以在插件市场更新。此外也可以在release界面下载插件的压缩包手动安装

**Comment by cx2c** [comment]
> 我们刚刚release了 0.3.0 版本，在这个插件中集成了 LSP，大部分常用功能与 VSCode 一致。目前插件市场正在审核中（通常需要2个工作日），审核完成后可以在插件市场更新。此外也可以在release界面下载插件的压缩包手动安装

好用！  0.3.0 版本的插件 体验直接拉满！
